### ISSUE TITLE
Issues under PHP 7

### ISSUE THREAD

**Issue by kricore** [joomlaworks/disqus-comments-for-joomla#5]
Under Joomla! 3.5 and PHP 7, there is this issue.

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgSystemJw_disqus has a deprecated constructor in /home/removedforprivacy/public_html/plugins/system/jw_disqus/jw_disqus.php on line 19

**Comment by fevangelou** [comment]
Fixed in 3.6.0 to be issued later in the day. Gracias :)
